# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Proyecto-02-SEP/GUITAR_HERO_HW/GUITAR_HERO_HW/Zybo-Z7-Master.xdc

# Block Designs: bd/diagrama_bloques/diagrama_bloques.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==diagrama_bloques || ORIG_REF_NAME==diagrama_bloques} -quiet] -quiet

# IP: bd/diagrama_bloques/ip/diagrama_bloques_processing_system7_0_0/diagrama_bloques_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==diagrama_bloques_processing_system7_0_0 || ORIG_REF_NAME==diagrama_bloques_processing_system7_0_0} -quiet] -quiet

# IP: bd/diagrama_bloques/ip/diagrama_bloques_axi_iic_0_0/diagrama_bloques_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==diagrama_bloques_axi_iic_0_0 || ORIG_REF_NAME==diagrama_bloques_axi_iic_0_0} -quiet] -quiet

# IP: bd/diagrama_bloques/ip/diagrama_bloques_ps7_0_axi_periph_0/diagrama_bloques_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==diagrama_bloques_ps7_0_axi_periph_0 || ORIG_REF_NAME==diagrama_bloques_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/diagrama_bloques/ip/diagrama_bloques_rst_ps7_0_50M_0/diagrama_bloques_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==diagrama_bloques_rst_ps7_0_50M_0 || ORIG_REF_NAME==diagrama_bloques_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/diagrama_bloques/ip/diagrama_bloques_xbar_0/diagrama_bloques_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==diagrama_bloques_xbar_0 || ORIG_REF_NAME==diagrama_bloques_xbar_0} -quiet] -quiet

# IP: bd/diagrama_bloques/ip/diagrama_bloques_BUZZER_AXI_0_1/diagrama_bloques_BUZZER_AXI_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==diagrama_bloques_BUZZER_AXI_0_1 || ORIG_REF_NAME==diagrama_bloques_BUZZER_AXI_0_1} -quiet] -quiet

# IP: bd/diagrama_bloques/ip/diagrama_bloques_Debouncer_0_0/diagrama_bloques_Debouncer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==diagrama_bloques_Debouncer_0_0 || ORIG_REF_NAME==diagrama_bloques_Debouncer_0_0} -quiet] -quiet

# IP: bd/diagrama_bloques/ip/diagrama_bloques_Debouncer_0_1/diagrama_bloques_Debouncer_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==diagrama_bloques_Debouncer_0_1 || ORIG_REF_NAME==diagrama_bloques_Debouncer_0_1} -quiet] -quiet

# IP: bd/diagrama_bloques/ip/diagrama_bloques_Debouncer_1_0/diagrama_bloques_Debouncer_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==diagrama_bloques_Debouncer_1_0 || ORIG_REF_NAME==diagrama_bloques_Debouncer_1_0} -quiet] -quiet

# IP: bd/diagrama_bloques/ip/diagrama_bloques_xlconcat_0_0/diagrama_bloques_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==diagrama_bloques_xlconcat_0_0 || ORIG_REF_NAME==diagrama_bloques_xlconcat_0_0} -quiet] -quiet

# IP: bd/diagrama_bloques/ip/diagrama_bloques_axi_gpio_0_0/diagrama_bloques_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==diagrama_bloques_axi_gpio_0_0 || ORIG_REF_NAME==diagrama_bloques_axi_gpio_0_0} -quiet] -quiet

# IP: bd/diagrama_bloques/ip/diagrama_bloques_axi_quad_spi_0_0/diagrama_bloques_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==diagrama_bloques_axi_quad_spi_0_0 || ORIG_REF_NAME==diagrama_bloques_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/diagrama_bloques/ip/diagrama_bloques_axi_gpio_1_0/diagrama_bloques_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==diagrama_bloques_axi_gpio_1_0 || ORIG_REF_NAME==diagrama_bloques_axi_gpio_1_0} -quiet] -quiet

# IP: bd/diagrama_bloques/ip/diagrama_bloques_axi_quad_spi_1_0/diagrama_bloques_axi_quad_spi_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==diagrama_bloques_axi_quad_spi_1_0 || ORIG_REF_NAME==diagrama_bloques_axi_quad_spi_1_0} -quiet] -quiet

# IP: bd/diagrama_bloques/ip/diagrama_bloques_auto_pc_0/diagrama_bloques_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==diagrama_bloques_auto_pc_0 || ORIG_REF_NAME==diagrama_bloques_auto_pc_0} -quiet] -quiet

# IP: bd/diagrama_bloques/ip/diagrama_bloques_axi_timer_0_0/diagrama_bloques_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==diagrama_bloques_axi_timer_0_0 || ORIG_REF_NAME==diagrama_bloques_axi_timer_0_0} -quiet] -quiet

# IP: bd/diagrama_bloques/ip/diagrama_bloques_xlconcat_1_0/diagrama_bloques_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==diagrama_bloques_xlconcat_1_0 || ORIG_REF_NAME==diagrama_bloques_xlconcat_1_0} -quiet] -quiet

# XDC: bd/diagrama_bloques/diagrama_bloques_ooc.xdc
