# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Proyecto-02-SEP/GUITAR_HERO_HW/GUITAR_HERO_HW/GUITAR_HERO_HW.srcs/sources_1/bd/diagrama_bloques/ip/diagrama_bloques_xbar_0/diagrama_bloques_xbar_0.xci
# IP: The module: 'diagrama_bloques_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Proyecto-02-SEP/GUITAR_HERO_HW/GUITAR_HERO_HW/GUITAR_HERO_HW.srcs/sources_1/bd/diagrama_bloques/ip/diagrama_bloques_xbar_0/diagrama_bloques_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'diagrama_bloques_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Proyecto-02-SEP/GUITAR_HERO_HW/GUITAR_HERO_HW/GUITAR_HERO_HW.srcs/sources_1/bd/diagrama_bloques/ip/diagrama_bloques_xbar_0/diagrama_bloques_xbar_0.xci
# IP: The module: 'diagrama_bloques_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Proyecto-02-SEP/GUITAR_HERO_HW/GUITAR_HERO_HW/GUITAR_HERO_HW.srcs/sources_1/bd/diagrama_bloques/ip/diagrama_bloques_xbar_0/diagrama_bloques_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'diagrama_bloques_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
